# docker build --build-arg gromacs_ver=2025.4 -t gromacs-gpu-2005.4 -f Dockerfile-gpu .

FROM nvidia/cuda:12.6.0-devel-ubuntu24.04
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

ARG gromacs_ver
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        cmake \
        wget \
        tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && wget --no-check-certificate https://ftp.gromacs.org/gromacs/gromacs-${gromacs_ver}.tar.gz \
    && tar zxvf gromacs-${gromacs_ver}.tar.gz \
    && cd gromacs-${gromacs_ver} \
    && mkdir -p /tmp/gromacs-${gromacs_ver}/build \
    && cd /tmp/gromacs-${gromacs_ver}/build \
    && cmake .. -DGMX_BUILD_OWN_FFTW=ON -DGMX_OPENMP=ON -DGMX_GPU=CUDA \
    && make \
    && make install \
    && rm -rf /tmp/gromacs-${gromacs_ver}*

ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home
