FROM nvidia/cuda:9.2-devel
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

RUN apt-get update \
    && apt-get install -y --no-install-recommends cmake g++ wget tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && wget http://ftp.gromacs.org/pub/gromacs/gromacs-2018.3.tar.gz \
    && tar zxvf gromacs-2018.3.tar.gz \
    && cd gromacs-2018.3 \
    && mkdir -p /tmp/gromacs-2018.3/build 

ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home

