FROM nvidia/cuda:9.2-runtime
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

COPY gromacs /usr/local/gromacs
ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home

