# docker build --build-arg gromacs_ver=2023.3 -t gromacs-mpi -f Dockerfile-mpi .

FROM ubuntu:20.04
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

ARG gromacs_ver
ENV DEBIAN_FRONTEND noninteractive
RUN apt update \
    && DEBIAN_FRONTEND='noninteractive'  apt install -y --no-install-recommends \
        cmake \
        g++ \
        libmpich-dev \
        libopenmpi-dev \
        make \
        openmpi-bin \
        openmpi-common \
        python3 \
        python3-dev \
        wget \
        tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && wget --no-check-certificate https://ftp.gromacs.org/gromacs/gromacs-${gromacs_ver}.tar.gz \
    && tar zxvf gromacs-${gromacs_ver}.tar.gz \
    && cd gromacs-${gromacs_ver} \
    && mkdir -p /tmp/gromacs-${gromacs_ver}/build

RUN cd /tmp/gromacs-${gromacs_ver}/build \
    && cmake .. -DGMX_BUILD_OWN_FFTW=ON -DGMX_MPI=ON -DMPIEXEC=srun -DMPIEXEC_NUMPROC_FLAG=-n  \
    && make \
    && make install \
    && rm -rf /tmp/gromacs-${gromacs_ver}*

ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home

