FROM centos:7
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

COPY gromacs.tgz /usr/local/gromacs.tgz

RUN yum -y update \
    && yum -y install epel-release tar wget \
    && yum -y update \
    && yum -y install \
        gcc-c++ \
        unzip \
        zip \
    && yum clean all \
    && cd /usr/local/ \
    && tar zxvf gromacs.tgz
  
ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home

