FROM ubuntu:20.04
LABEL maintainer="Mario David <mariojmdavid@gmail.com>"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        cmake \
        g++ \
        make \
        wget \
        tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && wget http://ftp.gromacs.org/pub/gromacs/gromacs-2022.tar.gz \
    && tar zxvf gromacs-2022.tar.gz \
    && cd gromacs-2022 \
    && mkdir -p /tmp/gromacs-2022/build \
    && cd /tmp/gromacs-2022/build \
    && cmake .. -DGMX_BUILD_OWN_FFTW=ON \
    && make \
    && make install \
    && rm -rf /tmp/gromacs-2022*

ENV PATH=$PATH:/usr/local/gromacs/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/gromacs/lib

WORKDIR /home

